In [22]:
import statistics

import pandas as pd

from helpers import *
from regression import *

In [23]:
pd.set_option('display.max_columns', None)

In [24]:
%load_ext autoreload
%autoreload 2

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload

In [25]:
# find_league_id('GB-ENG', 'Premier League')

In [26]:
CONFIG = {
    'elo_date': '2025-11-10',  # date for elo ratings from clubelo.com
    'opta_date': '2025-11-07',  # date for elo ratings from the opta -> clubelo regression; elo_date from day X is before the games are played, for opta it depends
    'number_of_sims': 10000,
    'league_id': 2,
    'season': 2025,
    'head_size': 36,
    'country_code_elo': 'UCL',  # use this attr. to use elo ratings from clubelo.com
    'country_code_api': None,  # use this attr. to use elo ratings from the opta -> clubelo regression
    'stdev': 0,
    'update_fixtures': True,
    'is_european_league': True,
}

In [27]:
# download_elo_data(CONFIG['elo_date'])

In [36]:
main_regression(**CONFIG)

468 ELO teams matched.
2 unmatched ELO teams found, see transformed/elo/elo_unmatched.csv:
484 Opta teams matched.
596 unmatched Opta teams found, see transformed/opta/opta_unmatched_map.csv:
820 unmatched Opta teams found, see transformed/opta/opta_unmatched_elo_df.csv:
465 teams used for regression.
0.9398 R^2 score
y = 24.91 * x + -422.48

In [29]:
standings_df = build_historical_standings_table_after_at_most_n_rounds(**CONFIG)
standings_df.head(CONFIG['head_size'])

                   Club   Elo  Points  Games played
1               Arsenal  2038      15             5
2        Bayern München  1993      12             5
3           Real Madrid  1946      12             5
4   Paris Saint Germain  1968      12             5
5                 Inter  1933      12             5
6       Manchester City  1997      10             5
7           Sporting CP  1799      10             5
8               Chelsea  1907      10             5
9     Borussia Dortmund  1852      10             5
10             Atalanta  1783      10             5
11            Liverpool  1979       9             5
12            Newcastle  1867       9             5
13      Atletico Madrid  1873       9             5
14          Galatasaray  1736       9             5
15        PSV Eindhoven  1791       8             5
16     Bayer Leverkusen  1852       8             5
17            Tottenham  1830       8             5
18            Barcelona  1933       7             5
19              Qarabag  1571       7             5
20               Napoli  1808       7             5
21                Pafos  1550       6             5
22             Juventus  1784       6             5
23   Union St. Gilloise  1726       6             5
24            Marseille  1755       6             5
25               Monaco  1716       6             5
26        FC Copenhagen  1595       4             5
27  Eintracht Frankfurt  1762       4             5
28       Club Brugge KV  1743       4             5
29        Athletic Club  1732       4             5
30              Benfica  1767       3             5
31         Slavia Praha  1683       3             5
32           Bodo/Glimt  1643       2             5
33   Olympiakos Piraeus  1681       2             5
34           Villarreal  1792       1             5
35        Kairat Almaty  1305       1             5
36                 Ajax  1594       0             5

In [30]:
float(round(standings_df['Points'].sum() / standings_df['Games played'].sum(), 2))

1.4

In [31]:
sample_season = simulate_season_after_n_rounds(**CONFIG, standings_df=standings_df)
sample_season.head(CONFIG['head_size'])

                   Club  Points   Elo  Games played
0               Arsenal      20  2038             8
5       Manchester City      19  1997             8
9              Atalanta      19  1783             8
2           Real Madrid      18  1946             8
4                 Inter      17  1933             8
1        Bayern München      17  1993             8
17            Barcelona      16  1933             8
10            Liverpool      16  1979             8
16            Tottenham      15  1830             8
14        PSV Eindhoven      15  1791             8
6           Sporting CP      14  1799             8
3   Paris Saint Germain      13  1968             8
7               Chelsea      13  1907             8
11            Newcastle      13  1867             8
12      Atletico Madrid      13  1873             8
20                Pafos      12  1550             8
18              Qarabag      11  1571             8
13          Galatasaray      11  1736             8
19               Napoli      11  1808             8
8     Borussia Dortmund      11  1852             8
28        Athletic Club      10  1732             8
24               Monaco      10  1716             8
21             Juventus       9  1784             8
23            Marseille       9  1755             8
15     Bayer Leverkusen       8  1852             8
27       Club Brugge KV       8  1743             8
25        FC Copenhagen       8  1595             8
32   Olympiakos Piraeus       7  1681             8
33           Villarreal       7  1792             8
22   Union St. Gilloise       6  1726             8
29              Benfica       6  1767             8
26  Eintracht Frankfurt       5  1762             8
34        Kairat Almaty       5  1305             8
31           Bodo/Glimt       5  1643             8
30         Slavia Praha       3  1683             8
35                 Ajax       1  1594             8

In [32]:
float(round(sample_season['Points'].sum() / sample_season['Games played'].sum(), 2))

1.39

In [33]:
# full table sim
results = run_full_table_sims(**CONFIG, standings_df=standings_df)
results.head(CONFIG['head_size'])

100%|██████████| 10000/10000 [01:06<00:00, 149.63it/s]

10000 simulations

,Club,Elo,xPts,Top 8,9 - 24,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36
1,Arsenal,2038,21.38,100.0,0.0,73.8,14.3,6.6,3.3,1.4,0.4,0.1,0.1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,Bayern München,1993,18.42,92.7,7.3,10.2,28.5,19.3,13.4,8.5,5.4,4.2,3.3,2.3,1.4,1.0,0.7,0.6,0.4,0.4,0.2,0.2,0.1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,Paris Saint Germain,1968,17.47,83.4,16.6,5.4,17.1,16.9,14.5,10.2,7.6,6.4,5.2,4.2,3.0,2.3,1.7,1.7,1.2,1.0,0.7,0.5,0.2,0.1,0.1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,Real Madrid,1946,17.45,84.3,15.7,5.1,16.2,17.3,14.1,10.8,8.5,6.7,5.6,4.3,3.3,2.4,1.6,1.1,0.9,0.8,0.5,0.4,0.2,0.1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
5,Inter,1933,16.15,64.1,35.9,3.7,6.7,9.2,10.4,9.9,8.6,8.0,7.6,7.1,6.1,4.4,4.4,3.8,3.2,2.6,2.0,1.1,0.7,0.3,0.1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
6,Manchester City,1997,15.89,65.2,34.8,0.8,6.4,8.4,8.9,10.5,11.5,10.5,8.3,6.1,5.5,5.4,4.6,4.0,2.7,1.7,1.2,1.1,0.9,0.6,0.4,0.3,0.2,0.1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
7,Chelsea,1907,15.53,56.6,43.3,0.5,4.2,5.9,7.6,10.0,11.0,9.6,7.8,7.0,6.1,6.5,5.6,5.2,3.9,2.8,1.9,1.2,1.0,0.8,0.5,0.4,0.3,0.2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
8,Borussia Dortmund,1852,14.79,43.0,56.9,0.2,2.5,3.9,5.6,7.8,8.5,7.4,7.2,6.6,6.7,7.2,7.4,6.5,5.2,4.3,3.2,2.3,2.3,2.2,1.4,0.8,0.5,0.3,0.1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
9,Liverpool,1979,14.71,40.4,59.4,0.0,0.9,3.6,5.8,5.6,6.3,8.3,9.8,9.7,8.0,6.8,6.0,5.2,5.2,5.1,4.0,3.0,2.2,1.7,0.9,0.5,0.5,0.5,0.2,0.1,0.1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
10,Atalanta,1783,14.24,33.0,66.8,0.2,1.5,2.9,4.1,5.8,6.4,6.3,5.8,5.7,7.3,7.3,7.7,6.8,6.4,4.9,4.4,3.8,3.6,3.2,2.4,1.3,0.9,0.7,0.4,0.1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
11,Atletico Madrid,1873,14.22,32.8,66.8,0.0,0.6,2.4,4.4,4.7,5.3,6.9,8.4,8.8,7.6,6.5,5.7,5.9,5.7,5.5,5.1,4.6,3.2,2.3,1.7,1.3,1.3,0.9,0.4,0.3,0.1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
12,Barcelona,1933,13.64,24.4,74.2,0.0,0.0,0.1,0.8,2.8,5.6,8.1,7.0,6.0,6.7,8.4,9.3,8.2,6.9,5.7,4.1,4.0,3.7,3.4,2.7,1.9,1.5,0.9,0.7,0.5,0.4,0.2,0.1,0.1,0.1,0.0,0.0,0.0,0.0,0.0,0.0
13,Bayer Leverkusen,1852,13.05,16.6,80.0,0.0,0.1,0.6,1.8,3.1,3.8,3.1,4.1,6.2,6.8,7.2,6.5,6.0,5.1,5.7,6.5,6.9,5.8,4.7,3.7,3.0,2.4,2.1,1.7,1.4,0.9,0.6,0.4,0.1,0.0,0.0,0.0,0.0,0.0,0.0,0.0
14,Sporting CP,1799,13.00,15.3,84.4,0.1,0.6,0.9,1.6,2.3,3.0,3.4,3.5,3.8,5.0,6.4,7.6,7.6,7.1,6.8,5.8,6.2,6.9,6.3,5.7,4.2,2.7,1.7,0.6,0.2,0.1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
15,Tottenham,1830,12.93,14.4,81.8,0.0,0.0,0.7,1.6,2.8,3.0,2.8,3.6,5.8,7.2,7.2,6.2,5.4,5.3,6.5,6.9,7.4,6.8,4.9,3.6,2.6,2.0,2.0,1.8,1.5,1.0,0.7,0.3,0.2,0.0,0.0,0.0,0.0,0.0,0.0,0.0
16,Newcastle,1867,12.82,14.3,84.0,0.0,0.2,0.9,1.2,1.8,2.3,3.3,4.6,4.9,5.2,5.5,5.4,6.6,7.3,7.6,7.7,7.0,5.7,4.9,4.3,3.8,3.4,2.9,1.9,1.1,0.4,0.1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
17,Galatasaray,1736,11.77,6.1,88.9,0.0,0.1,0.2,0.3,0.5,0.9,1.7,2.3,2.9,3.2,3.1,3.6,4.6,5.9,7.0,8.0,7.7,6.8,6.4,6.4,6.3,6.4,5.9,4.7,2.9,1.5,0.4,0.1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
18,Napoli,1808,11.32,4.6,82.0,0.0,0.0,0.0,0.2,0.7,1.1,1.2,1.4,1.7,2.4,3.6,4.8,5.3,5.5,4.7,5.2,5.9,7.8,8.0,7.6,6.4,4.9,4.4,4.0,3.7,3.1,2.2,1.7,1.4,0.8,0.4,0.1,0.0,0.0,0.0,0.0
19,Juventus,1784,11.26,2.6,84.0,0.0,0.0,0.0,0.0,0.0,0.2,0.8,1.6,2.7,2.8,2.6,2.9,4.3,6.0,7.2,7.4,7.6,7.0,6.3,6.2,5.9,5.5,5.3,4.5,3.4,2.9,1.9,1.6,1.4,1.2,0.6,0.3,0.1,0.0,0.0,0.0
20,PSV Eindhoven,1791,11.23,3.8,83.8,0.0,0.0,0.1,0.4,0.7,0.5,0.7,1.4,2.4,3.6,3.4,3.2,3.2,3.8,4.4,6.1,7.6,7.8,7.9,6.7,5.4,5.3,6.5,6.5,5.4,3.8,1.9,0.8,0.3,0.1,0.0,0.0,0.0,0.0,0.0,0.0
21,Qarabag,1571,9.74,0.4,66.4,0.0,0.0,0.0,0.0,0.1,0.0,0.1,0.2,0.3,0.4,0.8,1.4,2.0,2.8,2.5,2.8,3.0,4.8,7.2,8.3,8.5,8.2,6.7,6.8,7.0,6.9,6.8,5.4,3.9,2.1,0.9,0.1,0.0,0.0,0.0,0.0
22,Monaco,1716,9.43,0.5,61.9,0.0,0.0,0.0,0.0,0.0,0.0,0.2,0.3,0.5,0.5,0.5,0.8,1.3,2.1,3.0,4.0,4.3,4.1,4.3,5.2,6.7,8.3,8.3,8.0,7.4,6.3,5.7,5.4,5.1,3.8,2.5,1.1,0.2,0.0,0.0,0.0
23,Union St. Gilloise,1726,9.37,0.6,61.3,0.0,0.0,0.0,0.0,0.0,0.0,0.2,0.4,0.4,0.3,0.4,0.5,1.1,2.0,2.9,3.9,4.0,3.9,4.5,5.4,7.0,7.9,8.7,8.6,7.2,6.0,5.3,5.8,5.1,4.3,2.7,1.3,0.3,0.0,0.0,0.0
24,Marseille,1755,9.32,0.7,58.0,0.0,0.0,0.0,0.0,0.0,0.1,0.2,0.4,0.6,0.7,0.5,0.9,1.6,1.9,2.7,3.2,3.6,4.0,4.3,5.4,6.2,6.9,7.5,7.8,6.9,6.2,5.5,6.2,6.4,5.2,3.2,1.3,0.4,0.1,0.0,0.0
25,Club Brugge KV,1743,8.80,0.0,50.6,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.1,0.2,0.5,0.9,1.4,1.2,1.5,1.7,2.9,5.0,6.6,8.4,7.6,6.5,6.1,7.7,8.0,8.9,7.3,5.7,4.0,2.9,2.4,1.4,0.8,0.3,0.1
26,Pafos,1550,7.98,0.1,32.9,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.1,0.1,0.0,0.1,0.1,0.2,0.4,0.9,1.0,1.2,1.6,1.4,2.2,3.5,4.9,6.9,8.4,8.1,7.3,6.7,8.7,10.1,10.5,9.2,4.8,1.4,0.2,0.0,0.0
27,Eintracht Frankfurt,1762,7.75,0.0,31.5,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.1,0.2,0.5,0.5,0.6,0.5,0.6,1.0,1.8,2.9,3.8,4.9,4.5,4.4,5.1,6.9,8.6,8.6,8.1,8.0,6.8,7.1,6.7,5.1,2.4,0.4,0.0
28,Athletic Club,1732,7.22,0.0,22.7,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.1,0.2,0.4,0.5,0.5,0.4,0.9,1.4,2.1,2.6,2.7,3.5,3.2,4.2,5.6,7.8,8.6,8.3,7.8,8.0,8.8,10.0,8.0,3.6,0.8,0.1
29,Olympiakos Piraeus,1681,6.73,0.0,16.7,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.1,0.2,0.9,1.2,1.7,1.5,1.4,1.6,3.0,5.1,6.9,7.0,7.0,6.1,7.1,9.9,10.9,10.5,7.4,4.3,3.5,2.7
30,Benfica,1767,6.62,0.0,18.2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.1,0.2,0.4,0.8,0.5,0.8,0.9,1.5,2.2,2.9,3.8,4.2,4.6,4.6,6.0,7.5,8.3,9.7,10.2,9.5,10.0,8.1,3.1,0.4
31,Villarreal,1792,6.37,0.0,11.8,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.1,0.2,0.7,1.6,2.0,2.4,2.1,2.6,3.8,6.9,9.3,9.9,9.1,8.4,8.1,9.2,9.8,7.3,4.5,1.8
32,Slavia Praha,1683,6.10,0.0,12.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.2,0.2,0.3,0.2,0.4,0.6,0.7,1.2,2.0,2.8,3.3,3.3,4.2,5.1,7.0,8.3,10.2,11.0,11.6,12.6,9.9,4.6,0.3
33,FC Copenhagen,1595,5.87,0.0,7.3,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.1,0.0,0.1,0.1,0.1,0.1,0.4,0.5,0.7,1.1,1.2,1.2,1.6,2.6,4.4,5.9,6.5,7.4,8.0,9.9,14.7,18.8,11.5,2.8,0.2
34,Bodo/Glimt,1643,3.66,0.0,0.9,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.1,0.1,0.0,0.1,0.2,0.4,0.8,0.9,1.1,0.9,1.7,2.9,6.0,8.4,10.6,25.2,31.4,9.4
35,Ajax,1594,3.14,0.0,1.1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.3,0.4,0.4,0.4,0.6,1.0,1.7,2.3,3.5,4.4,5.8,8.6,18.6,24.3,27.8
36,Kairat Almaty,1305,1.95,0.0,0.1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.1,0.1,0.3,0.2,0.3,0.7,1.1,2.3,5.2,8.0,24.5,57.2

In [34]:
# # top 1
# results = run_multiple_sims(**CONFIG, standings_df=standings_df, number_of_winning_places=1)
# results.head(CONFIG['head_size'])

In [35]:
# # bottom 4
# results = run_multiple_sims(**CONFIG, standings_df=standings_df, number_of_winning_places=4, reverse=True)
# results.head(CONFIG['head_size'])